# 需在docker-compose.yml所在目录下运行
version: '3'
services:
  fpm:
    image: s709067323/fpm:latest
    volumes:
      - "./app:/app"
      - "./conf/fpm/php.ini:/usr/local/etc/php/php.ini:ro"
      - "./conf/fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
      - "./log/fpm:/var/log/php-fpm"
    networks:
      default:

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
      - "7001:7001"
      - "8018:8018"
    volumes:
      - "./app:/app"
      - "./conf/nginx/conf.d:/etc/nginx/conf.d/"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./log/nginx:/var/log/nginx"
    networks:
      default:
        # web 应用相互调用时需要设置域名映射
        aliases:
          - forum.test.com
          - p.test.com

  mysql:
    image: mysql:5.7
    command: "--innodb_use_native_aio=0" # win10 docker toolbox 下不加此命令无法启动
    restart: always
    ports:
      - "3306:3306" # 方便客户端连接
    volumes:
      - "./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro"
      - "./mysql:/var/lib/mysql"
      - "./log/mysql:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    # networks:
    #   default:

  redis:
    image: redis:4.0
    command: "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379" # 方便客户端连接
    volumes:
      - "./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      default:

  postgres:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432" # 方便客户端连接
    volumes:
      - "./conf/postgres/postgres.conf:/usr/share/postgresql/postgresql.conf"
      - "postgres-volume:/var/lib/postgresql/data" # 借助外部 volume 来实现数据持久化，避免 down 之后数据消失
      - "./log/postgres:/var/log/postgresql"
    environment:
      POSTGRES_PASSWORD: "123456"
    networks:
      default:

networks:
  default:

volumes:
  postgres-volume:
    external: true
  